- src/certAnalyser/analyserPool.go
- src/certRetriever/retrieverPool.go
- src/modules/amqpmodule/amqpmodule.go
- src/modules/elasticsearchmodule/elasticsearchmodule.go
From what I've seen so far the new code works nicely.
If you do not notice anything suspicious we can merge it to master and continue from there
> Cert push rework

- certificate/analyser.go
- conf/scanner.cfg
- config/config.go
Explicit truststore configuration.
Only path allowed for certain truststores.
> Remove ts from conf

- certificate/analyser.go
- certificate/certificate.go
- certificate/database.go
- connection/connection.go
- database/database.go
- tlsobs-api/handlers.go
- tlsobs-scanner/main.go
Just for review, so far.
Main functionality is there but needs some refinements and cljs incorporation.
> Api upgrade

- tlsobs-scanner/main.go
> Set completion to 100 when a target doesn't support TLS

- certificate/certificate.go
- tlsobs/main.go
$ go install github.com/mozilla/tls-observatory/tlsobs
$ tlsobs mozilla.org
This is pretty rough still, but it uses the API to run a scan and retrieve the results and the certificate.
@0xDiBa : r?
> Prototype for a command line client, fixes #47

- conf/api.cfg
- conf/scanner.cfg
- config/config.go
- tlsobs-api/main.go
- tlsobs-scanner/main.go
- tools/fixvalidity.go
The support for SSL in postgres is there, but not enabled by default because I'm getting a cert mismatch from RDS.
I also added a small Go script to fix the validity of existing certs in the database, by reparsing the raw certs.
@0xDiBa: r?
> Several database improvements

- database/messaging.go
Should I merge and close  #64?
> Pgmessagingv2

- tlsobs/main.go
- worker/mozillaEvaluationWorker/configurations.go
- worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go
- worker/mozillaEvaluationWorker/mozillaEvaluationWorker_test.go
- worker/worker.go
> Various cleanup and improvements to the evaluation worker

- conf/api.cfg
- config/config.go
- database/database.go
- database/schema.sql
- tlsobs-api/handlers.go
- tlsobs-api/main.go
After a long time :smile: ...
Solves #84 & #87
> API rate limiting

- conf/runner.yaml
> adding aus3 monitoring

- conf/runner.yaml
Adds grafana, login, stats, and cors-proxy
> Add more TC hosts

- conf/runner.yaml
> remove tracking.smc from runner

- tlsobs-scanner/workerconfig.go
- tlsobs/main.go
- tools/Dockerfile-scanner
- tools/extractCiphersuites.go
- worker/mozillaGradingWorker/cipherGrading.go
- worker/mozillaGradingWorker/ciphersuites.go
- worker/mozillaGradingWorker/keyexchangeGrading.go
- worker/mozillaGradingWorker/mozillaGradingWorker.go
- worker/mozillaGradingWorker/mozillaGradingWorker_test.go
- worker/mozillaGradingWorker/protocolGrading.go
cc @jvehent
Not sure if we are good to merge yet.
The grading is working fine, but the Key exchange grading part is not yet identical to the SSLLabs one ( really close though ).
> TLS grading

- Makefile
- certificate/certificate.go
- database/certificate.go
- database/schema.sql
- tools/fixSHA256SubjectSPKI.go
> Use parameterized queries instead of Sprintf

- conf/runner.yaml
I've removed APK endpoints as they are no longer valid. I've added another everything.me and Kinto endpoint. Also cleaned up a bunch of white space chars (thanks vim).
r?
> Add and remove entries from runner configuration

- tlsobs/main.go
> sort analysis array before showing it. fixes #131

- conf/runner.yaml
> Add sync sites to runner config

- tlsobs/main.go
> Remove https prefix

- Dockerfile
- tools/Dockerfile-api
- tools/Dockerfile-scanner
> fix dockerfiles

- static/certsplainer.html
- static/certsplainer.js
This is a rebased version of #191 with the patch from https://github.com/mozilla/tls-observatory/pull/191#issuecomment-274352475.
I ran through the functional tests in that comment as well.
> Minor cleanup

- Makefile
- certificate/certificate.go
- database/certificate.go
- database/schema.sql
- tlsobs-scanner/main.go
- tlsobs-scanner/workerconfig.go
- worker/ciscoUmbrellaRank/ciscoUmbrellaRank.go
This patch adds a worker that evaluates the ranking of a domain on the cisco umbrella list and stores it in database.
> Cisco Umbrella ranking

- conf/runner.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1344070
r?
> Notify IT for telemetry-experiment.cdn.mozilla.net

- conf/runner.yaml
Updated production sync node.
Added stage sync node.
r? @jvehent
> Updates for Sync.

- conf/runner.yaml
> remove browserid.org (and diresworb.org)

- conf/runner.yaml
> Add fxpartners.mozilla.com to runner config

- conf/runner.yaml
> Add additional metrics related endpoints to runner config

- conf/runner.yaml
> Updates to runner config for AMO

- conf/api.cfg
- config/config.go
- tlsobs-api/main.go
Not sure whether we want this to be configurable through the config file/environment variables or through command line arguments.
> Make API listen address configurable

- database/database.go
> Make scan attempts start at 0

- conf/runner.yaml
> Update Data Platform services alert recipient

- worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go
> fix a typo (s/leved/level) in mozillaEvaluationWorker

- docker-compose.yml
- tools/Dockerfile-postgres
Added a docker compose file to run the api, scanner and postgres
> Added docker-compose

- .circleci/config.yml
- Makefile
- worker/top1m/top1m.go
Cisco Umbrella and Alexa have vastly different ranking of top1m domains. This patch stores both so we can make more intelligent queries.
> top1m: add alexa ranking

- conf/runner.yaml
> Remove marketplace* Bug 1432964

- conf/runner.yaml
> Add probeinfo.telemetry.mozilla.org Bug 1444942

- worker/crlWorker/crlWorker.go
Probably exposed from #329 now that the CRL worker is merged.
> worker/crlWorker: fixup printf interpolations

- conf/runner.yaml
> Add public-data.telemetry.mozilla.org Bug 1455725

- tools/initMozPolicy.go
There was a wild fire which came up to the property and forced a short evacuation, so I didn't get to test this.
> Added tool to initialize the mozilla policy field

- conf/runner.yaml
> Data platform updates

- worker/evCheckerWorker/evCheckerWorker.go
<Describe your changes here, add references to any issue>
> Fix evchecker output

- conf/runner.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1492656
r?
> Add coverage-bug1492656.mozilla.org

- Dockerfile
- worker/awsCertlint/awsCertlint.go
> bump to go1.11

- conf/runner.yaml
I realized I'd never updates this as domains were added.
> Updates for services bpitts works on

- conf/runner.yaml
> runner.yaml: add cdn.stubdownloader.services.mozilla.com

- static/index.html
> remove migration notice

- conf/runner.yaml
Decommed in https://bugzilla.mozilla.org/show_bug.cgi?id=1612595
> runner.yaml: remove aus3.mozilla.org

- conf/runner.yaml
<Describe your changes here, add references to any issue>
> runner.yaml: add detectportal.firefox.com

- conf/runner.yaml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1668955 for more details
> Remove aus4 monitoring

- conf/runner.yaml
> Remove decommissioned data services from runner.yaml

- .gitmodules
<Describe your changes here, add references to any issue>
> submodule url for cipherscan exists not more, updated

- kubernetes/deployment.yaml
Update the dev k8s config to work with newer k8s versions (test locally with minikube v1.16.0 and k8s v1.20.0)
> Update k8s config

- README.md
<Describe your changes here, add references to any issue>
> readme: add newlines around code snippets and lists
