mozilla/tls-observatory

modules/postgresmodule/schema.sql
This schema should support multiple chain of trusts per certificate, as well as updating the status of a chain of trust over time.
r? @0xDiBa @marumari
=> Update to the DB schema to support chains of trust

certificate/certificate.go, database/certificate.go, database/schema.sql, tools/fixsubjectNames.go
The proposed change breaks the current database schema as the issuer and subject fields are going from varchar to jsonb.
I think dropping and recreating these columns is the best thing we can do. 
Should I create a script to go through the whole certificates table, parse certificates and save the new form of the issuer and subject fields?
=> issuer and subject are now jsonb fields

conf/api.cfg, conf/scanner.cfg, config/config.go, database/database.go, database/messaging.go, database/schema.sql, tlsobs-scanner/main.go, worker/mozillaEvaluationWorker/configurations.go, worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go, worker/mozillaEvaluationWorker/mozillaEvaluationWorker_test.go
do not merge yet, testing in staging first
This set of patches improves the evaluation worker and add some stricter controls on the number of scanners that run in parallel. We also store a number column in the `scans` table to track a count of retries on scans that don't succeeds.
This last change requires a DB change:
```sql
ALTER TABLE scans ADD COLUMN attempts integer;
```
=> Evaluation worker & scanners limits rework

conf/runner.yaml
Getting TC hosts setup within the runner.yaml config.  My expectation is the email recipient will be adjusted to the TC team when there is a better understanding for what level is required by each node.
=> Add TaskCluster HTTPS endpoints for testing

worker/mozillaEvaluationWorker/configurations.go, worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go
The evaluation worker gets the configuration from https://statics.tls.security.mozilla.org/server-side-tls-conf-4.0.json .
In case they are not available at that URL or the unmarshalling fails for any reason the ones saved locally are used.
Would it be worth it removing the version from the file, so going to server-side-tls-conf.json ? ( since the version is in the file and the evaluation worker should always get the latest without recompiling )
=> TLS configuration from static resource

README.md, certificate/certificate.go, certificate/paths.go, database/certificate.go, tlsobs-api/handlers.go, tlsobs-api/logger.go, tlsobs-api/router.go
This is a large patch to add a new endpoint that accepts certificates submitted directly through the API. Most of the code is fairly straighforward, up until we get to the path building code. You see, the API does not have loaded truststores, and it seems silly to load them from local files when the database already has all the information needed. So I implemented path building using data in the certificate table. It's rather crude, and could probably be improved, but it gets the job done and has the benefit of checking for certificates signatures, so we know there isn't any false positive in the path.
@0xdiba, would you do me the honors of a review?
=> Add API endpoint to POST certificates

certificate/certificate.go, database/certificate.go, database/schema.sql, tools/fixSHA256SubjectSPKI.go
This patch adds support for computing a hash of the raw subject and spki fields of a certificate and storing it in database. The new field is called `sha256_subject_spki` in both the DB and JSON output. It represents the hexadecimal string of the SHA256 of DER encoded Subject and SPKI fields.
Before deploying this to prod, we'll need to run this query: `ALTER TABLE certificates ADD COLUMN sha256_subject_spki;`
Then run the tool to update existing rows: `go run fixSHA256SubjectSPKI.go`
And finally set the `NOT NULL` condition on the column: `ALTER TABLE certificates ALTER COLUMN sha256_subject_spki SET NOT NULL;`
r? @mozkeeler
f? @sleevi (and thanks for the code snippet)
=> Add Subject+SPKI hashing to certificate parsing

tlsobs/main.go
Reverts mozilla/tls-observatory#150
So, I just realized this isn't what we want. We want to sort the analysis array in the JSON returned by the API, not just sort the display in the tlsobs command line.
=> Revert "sort analysis array before showing it. fixes #131"

tools/pullCTLogs.go
change the filename to the hash of the certificate, that is always non-empty.
=> PostCertificateHandler is not able to handle empty filenames

README.md, database/certificate.go, tlsobs-api/handlers.go, tlsobs-api/router.go
Locally I saw some differences between https://tls-observatory.services.mozilla.com/api/v1/certificate?id=42 and http://localhost/api/v1/certificate?id=42. I'm not exactly sure why this is, but I wanted to mention it just in case.
Missing:
=> Added truststore endpoint

worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go, worker/worker.go
Based on discussion for #193 .
=> Lazily setup evaluation worker

database/database.go
URL building for database connections does not rfc2396 encode user credentials
=> 201 - rfc2396 those user creds

conf/runner.yaml
The frontend portion of the service has been decommissioned.
=> Remove miracle service from runner config

database/certificate.go, tlsobs-api/handlers.go, tools/pullCTLogsIntoDB.go
Cross-signing in the web pki apparently contains a lot of infinite loops
that break the building of paths. This patch implement a simple []string
that contains the CNs of certs that have already been seen in the path,
to prevent the function from looping indefinitely.
=> Prevent infinite loops from breaks certificate paths building

database/certificate.go, database/database.go, tlsobs-api/insert_test.go
```
Before the optimization: BenchmarkInsertNewCertificate-8   	     100	  16625509 ns/op
After the optimization:  BenchmarkInsertNewCertificate-8   	     100	  11918866 ns/op
```
So ~30% faster now.
There's still plenty to optimize, as there's another N+1 problem with the truststore validation checks. My guess is that will also add another 30% speed improvement.
=> Certificate insert optimizations

README.md, conf/runner.yaml, tlsobs-runner/main.go, tlsobs-runner/main_test.go, tlsobs-runner/notifications.go
This commit adds the option of sending a slack message via webhook when a notification needs to be sent.
Included:
* sample config in `conf/runner.yaml`. Each run can have multiple channels to send notifications to, but each config file (and therefore each runner) only supports one username, one icon, and one webhook. 
* parsing slack config in `tlsobs-runner/main.go`, as well as the ability to override slack config with environment variables
* post request logic in `tlsobs-runner/notifications.go`
* environment override logic tests in `tlsobs-runner/main_test.go`
=> Added slack webhook notification option

conf/runner.yaml
persona and universalsearch are dead
pageshot is now screenshots
normandy has two more urls
embedly-proxy is tiles not testpilot
=> Update relud's projects in tls-observatory

tlsobs-api/handlers.go, tlsobs-api/router.go, version.json
Adds `/__heartbeat__`, `/__lbheartbeat__` and `/__version__` endpoints.
The `/__version__` endpoint will require some automation in CI to work, as the `version.json` file needs to be generated.
=> Add Dockerflow endpoints

database/certificate.go, database/database.go, vendor/github.com/hashicorp/golang-lru/2q.go, vendor/github.com/hashicorp/golang-lru/2q_test.go, vendor/github.com/hashicorp/golang-lru/LICENSE, vendor/github.com/hashicorp/golang-lru/README.md, vendor/github.com/hashicorp/golang-lru/arc.go, vendor/github.com/hashicorp/golang-lru/arc_test.go, vendor/github.com/hashicorp/golang-lru/lru.go, vendor/github.com/hashicorp/golang-lru/lru_test.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru_test.go
This is a fairly crude implementation of a paths cache that simply stores the most recent 10,000 paths in an ARC Cache (LRU-type struct). It works in my local tests, and I think it will significantly speed up certificates insertion.
=> #211: Cache issuers (and their paths) chaining to built-in roots

conf/runner.yaml
This is a deprecated endpoint but is still being used by old clients.
=> Add data.mozilla.com to runner config

config/config.go, tlsobs-api/main.go, tlsobs-api/router.go, worker/evCheckerWorker/config.go, worker/evCheckerWorker/evCheckerWorker.go, worker/top1m/top1m.go
- top-1m.csv
- truststore location
- cipherscan location
- static asset location
- ev-checker location
top1m and ev-checker config can't be in config.go because there's currently no way to pass any configuration to workers.
=> Make several things configurable through env vars

bin/ci/deploy_dockerhub.sh
Fixes broken deploy_dockerhub script.
No need to check whether we're passing in `master`, as we always pass in `latest` and the commit hash.
=> Fix deploy_dockerhub

certificate/certificate.go, certificate/certificate_test.go, tools/fixserialnumber.go
Fixes #218 
This patch changes the way we store the serial number in the database. Currently, we store the hex representation of the serial number. This patch stores the hex representation of the DER-encoded serial number. A few examples of what currently happens and what will happen after the patch:
| Serial Number (Decimal) | Currently stored | Stored after patch |
|-------------------------|------------------|--------------------|
| 1                       | 1                | 01                 |
| -1                      | -1               | FF                 |
| 0                       | 0                | 00                 |
| 201                     | C9               | 00C9               |
| -201                    | -C9              | FF37               |
You can try more …
=> Fix leading serial number zeroes not being included in the database

Dockerfile
Moving the binaries broke some people's workflows, e.g. #248. Copying will restore backwards-compatibility.
=> Dockerfile: copy binaries instead of moving them

Dockerfile, README.md, kubernetes/README.md, kubernetes/deployment.yaml, kubernetes/setup_db.yaml
This adds a simple Kubernetes configuration that runs postgres, the api and the scanner I used a few days ago to try to reproduce a bug.
I don't know if we prefer docker-compose (#171) over kubernetes.
=> Add Kubernetes deployment

worker/mozillaEvaluationWorker/mozillaEvaluationWorker.go
Add the ECDHE-RSA-CHACHA20-POLY1305-OLD cipher to the ignored ciphers added for #186 as this is also used by cloudflare on sites that have a RSA certificate as noted in #226
=> Add exception for RSA CHACHA20 cipher to fix cloudflare sites with RSA certs being marked as insecure

README.md
These didn't work on github's page. Do y'all use a different web interface for git repos? 
You can view them working for github: 
https://github.com/adamdecaf/tls-observatory/tree/readme-links-fix
=> docs: fix readme API endpoint links

conf/scanner.cfg, connection/retriever.go, database/database.go, database/schema.sql, tlsobs-scanner/main.go, tlsobs/main.go
Trying to prevent scans from hanging forever, which slows down scanners. I also added some code to expose the timeout information in the cmdline tool through the API.
=> Timeout cipherscan after 3 minutes

tlsobs/main.go
Running something like this failed, which surprised me for a bit. 
```
$ ~/code/bin/tlsobs -observatory http://localhost:8083 -r https://revoked.badssl.com/ 
Scanning https://revoked.badssl.com/ (id 8)
Retrieving cached results from 1.010450033s ago. To run a new scan, use '-r'.
revoked.badssl.com/ does not support SSL/TLS
```
=> tlsobs: Trim trailing slash from target

connection/retriever.go
I had an old version of bash, but didn't find out until running `cipherscan` manually.
=> connection: Print stderr from running cipherscan

conf/runner.yaml
The service is decommissioned per
* https://bugzilla.mozilla.org/show_bug.cgi?id=1432964
* https://bugzilla.mozilla.org/show_bug.cgi?id=1447049
=> Stop monitoring everything.me

README.md, tlsobs-scanner/workerconfig.go, tlsobs/main.go, tools/Dockerfile-scanner, worker/awsCertlint/awsCertlint.go
Fixes: https://github.com/mozilla/tls-observatory/issues/257 
```
--- Analyzers ---
* awslabs/certlint Results
- No messages
```
```
--- Analyzers ---
* awslabs/certlint Results
- Notice: Some python versions will not see SAN extension if it is the first extension	awslabs-certlint780452766
```
=> add awsCertlint worker

.circleci/config.yml, README.md, certificate/certificate.go, certificate/constraints/constraints.go
Part of the change from https://github.com/mozilla/tls-observatory/pull/322, but without the deletion of that vendor folder.
**This change requires Go 1.10+ now**, because of the additional fields on `certificate.Certificate`.
=> Switch off constraintscrypto, require Go 1.10 

database/migrations/1.3.3.sql, database/schema.sql
When adding new columns, existing certs must be updated to prevent the parsing to fail.
=> Fix creation of EKU OID column

certificate/certificate.go, database/certificate.go, database/migrations/1.3.5.sql, database/schema.sql, static/certsplainer.html, static/certsplainer.js, tools/fixSHA256SubjectSPKI.go
In 1.2.37, I removed support for Subject SPKI (#144) and turned the value into standard SPKI. Turns out this was a mistake, and Subject SPKI is very much needed by CCADB. This patch re-adds it into a new column.
=> Re-add support for Subject SPKI hash

tools/MozillaSites.txt
removing 2 domains that are deprecated
=> Bug 1471541 - api.pub.build.mozilla.org url is deprecated

conf/runner.yaml
download-sha1.cdn.mozilla.net is expiring in 2 weeks and not being renewed
=> Remove download-sha1.cdn.mozilla.net

conf/runner.yaml
THis configures the general monitoring that will email us after 35 days, and will also page us for the two prod deployments if unaddressed with 14 days remaining.
cc @edunham
=> Taskcluster: New domains

conf/runner.yaml
We are retiring this endpoint; see https://bugzilla.mozilla.org/show_bug.cgi?id=1614692
=> Socorro: remove crash-reports-xpsp2

.circleci/config.yml
Add 10m timeout to CI "Run a simple test scan".  It currently consumes 5h of CCI time before failing (normally it'd fail about 30m w/o output) and there isn't a way to set a timeout in CCI.
r? @Micheletto
=> ci: timeout and kill simple scan step after 10m

.circleci/config.yml
Disable the test scan so we can publish a new version to dockerhub
=> ci: disable test scan

.circleci/config.yml, Dockerfile, README.md
Update CI and docker image to a supported golang version
=> bump golang version to 1.15

database/certificate.go, tlsobs-scanner/analyser.go
batch cert `last_seen` updates to reduce DB lock contention
refs: https://gist.github.com/g-k/7d2e8835399018a51a0407fb4337d75a and prior poking with @Micheletto 
NB: `gofmt` and `golint` have a pile of changes and warnings
I haven't run perf tests, but should be able to verify the changes in stage.
r? @ajvb
=> scanner: batch cert last_seen updates to reduce DB lock contention

conf/runner.yaml
l10n.mozilla.org was decommed a while back. This is now a redirect that
lives in refractr. It is monitored by Web SRE and should not page
anyone.
=> Remove monitring for elmo
